<a href="https://colab.research.google.com/github/sravanidaragani12-stack/SQTS-Data-Analytics-Internship/blob/main/TASK2_Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded = files.upload()

Saving retail_store_sales.csv.xlsx to retail_store_sales.csv.xlsx

In [2]:
import pandas as pd
df = pd.read_excel("retail_store_sales.csv.xlsx")

In [3]:
df.head()

,Transaction ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Transaction Date,Discount Applied
0,TXN_6867343,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,2024-04-08,1.0
1,TXN_3731986,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,2023-07-23,1.0
2,TXN_9303719,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,2022-10-05,0.0
3,TXN_9458126,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,2022-05-07,NaN
4,TXN_4575373,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,2022-10-02,0.0

In [4]:
df["Transaction ID"]

0        TXN_6867343
1        TXN_3731986
2        TXN_9303719
3        TXN_9458126
4        TXN_4575373
            ...
12570    TXN_9347481
12571    TXN_4009414
12572    TXN_5306010
12573    TXN_5167298
12574    TXN_2407494
Name: Transaction ID, Length: 12575, dtype: object

In [5]:
df["Transaction ID"].isnull().sum()

np.int64(0)

In [6]:
df["Category"]

0           Patisserie
1        Milk Products
2             Butchers
3            Beverages
4                 Food
             ...
12570       Patisserie
12571        Beverages
12572         Butchers
12573        Furniture
12574             Food
Name: Category, Length: 12575, dtype: object

In [7]:
df["Category"].isnull().sum()

np.int64(0)

In [8]:
df["Item"]

0         Item_10_PAT
1        Item_17_MILK
2         Item_12_BUT
3         Item_16_BEV
4         Item_6_FOOD
             ...
12570     Item_23_PAT
12571      Item_2_BEV
12572      Item_7_BUT
12573      Item_7_FUR
12574     Item_9_FOOD
Name: Item, Length: 12575, dtype: object

In [9]:
df["Item"].isnull().sum()

np.int64(1213)

In [10]:
df.isnull().sum()

Transaction ID         0
Category               0
Item                1213
Price Per Unit       609
Quantity             604
Total Spent          604
Payment Method         0
Transaction Date       0
Discount Applied    4199
dtype: int64

In [11]:
df=df.dropna(subset=["Item"])

In [12]:
df["Item"].isnull().sum()

np.int64(0)

In [13]:
df["Price Per Unit"]

0        18.5
1        29.0
2        21.5
3        27.5
4        12.5
         ...
12570    38.0
12571     6.5
12572    14.0
12573    14.0
12574    17.0
Name: Price Per Unit, Length: 11362, dtype: float64

In [14]:
df["Price Per Unit"].isnull().sum()

np.int64(0)

In [15]:
df["Quantity"]

0        10.0
1         9.0
2         2.0
3         9.0
4         7.0
         ...
12570     4.0
12571     9.0
12572    10.0
12573     6.0
12574     3.0
Name: Quantity, Length: 11362, dtype: float64

In [16]:
df["Quantity"].isnull().sum()

np.int64(0)

In [17]:
df["Total Spent"]

0        185.0
1        261.0
2         43.0
3        247.5
4         87.5
         ...
12570    152.0
12571     58.5
12572    140.0
12573     84.0
12574     51.0
Name: Total Spent, Length: 11362, dtype: float64

In [18]:
df["Total Spent"].isnull().sum()

np.int64(0)

In [19]:
df["Payment Method"]

0        Digital Wallet
1        Digital Wallet
2           Credit Card
3           Credit Card
4        Digital Wallet
              ...
12570       Credit Card
12571              Cash
12572              Cash
12573              Cash
12574              Cash
Name: Payment Method, Length: 11362, dtype: object

In [20]:
df["Payment Method"].isnull().sum()

np.int64(0)

In [21]:
df["Transaction Date"]

0       2024-04-08
1       2023-07-23
2       2022-10-05
3       2022-05-07
4       2022-10-02
           ...
12570   2023-09-03
12571   2022-08-12
12572   2024-08-24
12573   2023-12-30
12574   2022-08-06
Name: Transaction Date, Length: 11362, dtype: datetime64[ns]

In [22]:
df["Transaction Date"].isnull().sum()

np.int64(0)

In [23]:
df["Discount Applied"]

0        1.0
1        1.0
2        0.0
3        NaN
4        0.0
        ...
12570    NaN
12571    0.0
12572    NaN
12573    1.0
12574    NaN
Name: Discount Applied, Length: 11362, dtype: float64

In [24]:
df["Discount Applied"].isnull().sum()

np.int64(3783)

In [25]:
df[pd.to_numeric(df["Discount Applied"], errors="coerce").isnull()]

,Transaction ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Transaction Date,Discount Applied
3,TXN_9458126,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,2022-05-07,NaN
14,TXN_2490363,Milk Products,Item_16_MILK,27.5,2.0,55.0,Digital Wallet,2022-05-22,NaN
20,TXN_9939063,Beverages,Item_7_BEV,14.0,9.0,126.0,Digital Wallet,2024-01-14,NaN
22,TXN_6547964,Electric household essentials,Item_4_EHE,9.5,7.0,66.5,Cash,2022-08-15,NaN
33,TXN_1494700,Electric household essentials,Item_21_EHE,35.0,9.0,315.0,Credit Card,2024-03-07,NaN
...,...,...,...,...,...,...,...,...,...
12551,TXN_3673685,Beverages,Item_12_BEV,21.5,10.0,215.0,Digital Wallet,2024-08-20,NaN
12568,TXN_1096134,Food,Item_4_FOOD,9.5,8.0,76.0,Digital Wallet,2022-06-11,NaN
12570,TXN_9347481,Patisserie,Item_23_PAT,38.0,4.0,152.0,Credit Card,2023-09-03,NaN
12572,TXN_5306010,Butchers,Item_7_BUT,14.0,10.0,140.0,Cash,2024-08-24,NaN
12574,TXN_2407494,Food,Item_9_FOOD,17.0,3.0,51.0,Cash,2022-08-06,NaN

In [26]:
df["Discount Applied"] = pd.to_numeric(df["Discount Applied"], errors="coerce")

In [27]:
invalid_discounts = df[(df["Discount Applied"] < 0) | (df["Discount Applied"] > 100)]

In [28]:
df = df[(df["Discount Applied"] >= 0) & (df["Discount Applied"] <= 100)]

In [29]:
df["Discount Applied"].isnull().sum()

np.int64(0)

In [30]:
df["Total Revenue"] = df["Quantity"] * df["Price Per Unit"]

In [31]:
df.head()

,Transaction ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Transaction Date,Discount Applied,Total Revenue
0,TXN_6867343,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,2024-04-08,1.0,185.0
1,TXN_3731986,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,2023-07-23,1.0,261.0
2,TXN_9303719,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,2022-10-05,0.0,43.0
4,TXN_4575373,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,2022-10-02,0.0,87.5
6,TXN_3652209,Food,Item_1_FOOD,5.0,8.0,40.0,Credit Card,2023-06-10,1.0,40.0

In [32]:
df.drop("Payment Method", axis=1, inplace=True)

In [33]:
df

,Transaction ID,Category,Item,Price Per Unit,Quantity,Total Spent,Transaction Date,Discount Applied,Total Revenue
0,TXN_6867343,Patisserie,Item_10_PAT,18.5,10.0,185.0,2024-04-08,1.0,185.0
1,TXN_3731986,Milk Products,Item_17_MILK,29.0,9.0,261.0,2023-07-23,1.0,261.0
2,TXN_9303719,Butchers,Item_12_BUT,21.5,2.0,43.0,2022-10-05,0.0,43.0
4,TXN_4575373,Food,Item_6_FOOD,12.5,7.0,87.5,2022-10-02,0.0,87.5
6,TXN_3652209,Food,Item_1_FOOD,5.0,8.0,40.0,2023-06-10,1.0,40.0
...,...,...,...,...,...,...,...,...,...
12566,TXN_6298574,Milk Products,Item_1_MILK,5.0,4.0,20.0,2023-05-09,0.0,20.0
12567,TXN_4890318,Butchers,Item_3_BUT,8.0,5.0,40.0,2023-03-28,0.0,40.0
12569,TXN_2318174,Patisserie,Item_1_PAT,5.0,9.0,45.0,2024-05-13,0.0,45.0
12571,TXN_4009414,Beverages,Item_2_BEV,6.5,9.0,58.5,2022-08-12,0.0,58.5
12573,TXN_5167298,Furniture,Item_7_FUR,14.0,6.0,84.0,2023-12-30,1.0,84.0

In [34]:
df.columns

Index(['Transaction ID', 'Category', 'Item', 'Price Per Unit', 'Quantity',
       'Total Spent', 'Transaction Date', 'Discount Applied', 'Total Revenue'],
      dtype='object')

In [35]:
df.shape
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 7579 entries, 0 to 12573
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    7579 non-null   object
 1   Category          7579 non-null   object
 2   Item              7579 non-null   object
 3   Price Per Unit    7579 non-null   float64
 4   Quantity          7579 non-null   float64
 5   Total Spent       7579 non-null   float64
 6   Transaction Date  7579 non-null   datetime64[ns]
 7   Discount Applied  7579 non-null   float64
 8   Total Revenue     7579 non-null   float64
dtypes: datetime64[ns](1), float64(5), object(3)
memory usage: 592.1+ KB

,Price Per Unit,Quantity,Total Spent,Transaction Date,Discount Applied,Total Revenue
count,7579.000000,7579.000000,7579.000000,7579,7579.000000,7579.000000
mean,23.428882,5.557329,130.427893,2023-07-11 13:57:42.250956544,0.501517,130.427893
min,5.000000,1.000000,5.000000,2022-01-01 00:00:00,0.000000,5.000000
25%,14.000000,3.000000,52.000000,2022-09-27 00:00:00,0.000000,52.000000
50%,23.000000,6.000000,110.000000,2023-07-09 00:00:00,1.000000,110.000000
75%,33.500000,8.000000,192.000000,2024-04-28 00:00:00,1.000000,192.000000
max,41.000000,10.000000,410.000000,2025-01-18 00:00:00,1.000000,410.000000
std,10.704121,2.843546,94.378663,NaN,0.500031,94.378663

In [36]:
df["Location"] = "Hyderabad"

In [37]:
import numpy as np

df["Location"] = np.random.choice(
    ["Hyderabad", "Chennai", "Mumbai", "Bangalore"],
    len(df)
)

In [38]:
df["Location"].value_counts()

Location
Bangalore    1933
Chennai      1920
Hyderabad    1894
Mumbai       1832
Name: count, dtype: int64

In [39]:
df["Location"].value_counts()

Location
Bangalore    1933
Chennai      1920
Hyderabad    1894
Mumbai       1832
Name: count, dtype: int64

In [40]:
df.columns

Index(['Transaction ID', 'Category', 'Item', 'Price Per Unit', 'Quantity',
       'Total Spent', 'Transaction Date', 'Discount Applied', 'Total Revenue',
       'Location'],
      dtype='object')

In [41]:
import numpy as np

df["Payment Method"] = np.random.choice(
    ["Cash", "Card", "UPI", "Net Banking"],
    len(df)
)

In [42]:
df.columns

Index(['Transaction ID', 'Category', 'Item', 'Price Per Unit', 'Quantity',
       'Total Spent', 'Transaction Date', 'Discount Applied', 'Total Revenue',
       'Location', 'Payment Method'],
      dtype='object')

In [43]:
df["Payment Method"].value_counts()

Payment Method
UPI            1945
Card           1935
Net Banking    1871
Cash           1828
Name: count, dtype: int64

In [44]:
df.to_csv("cleaned_sales_data.csv", index=False)

df